### PR TITLE
Sync Deltaspike BeanManagerProvider with upstream: JDF-220 + license cor...

### PR DESCRIPTION
**Pull request by rsmeral**
...rections

### CODE REVIEW

**Comment by pmuir** [comment]
@rsmeral could you split this into multiple commits, one for the whitespace and license changes and one or more (as relevant) for the functional changes (each functional change should be one commit) and make sure your commit message reflects the actual change.

**Comment by rsmeral** [comment]
I just merged commits jboss-jdf/jboss-as-quickstart@b8f93afc .. jboss-jdf/jboss-as-quickstart@ac28d261. One of them is "Correction for JDF-220 and License Headers for deltaspike-beanmanagerprovider" which has the functional changes and license changes mixed. Is it necessary to go through the laborious process of splitting it?

**Comment by pmuir** [comment]
@rsmeral yes :-) It's normal to try to not mix formatting changes with functional changes, and to submit one commit per issue.

**Comment by rsmeral** [comment]
@pmuir Acceptable now?  :)

**Pull request closed without merging**
