### PR TITLE
Remove wfk quickstarts

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by kpiwko** [comment]
Applying pull request on top of master-eap6 seems fine.

The only glitch is that jboss-as-jax-rs-client test fails.

**Comment by pmuir** [comment]
Yes, you need to disable certain tests for running tests from root to work i.e. -Dcomplex-dependencies=disabled

**Comment by kpiwko** [comment]
Yes, I've already done that.

**Comment by pmuir** [comment]
Stil fails when you run manually as per the README? (deploying helloworld-rs first)

**Comment by kpiwko** [comment]
Nope, it works fine when prerequisites are fulfilled.

**Comment by sgilda** [comment]
Pushed to eap-master

**Pull request closed without merging**
