### PR TITLE
Remove jax-rs-client to allow build to succeed from root directory

### PR DESCRIPTION
**Pull request by sgilda**
Please check this fix carefully to make sure it's correct before you merge!!!

### CODE REVIEW

**Comment by sgilda** [comment]
Per @pmuir:
This is not a good solution. It will break Eclipse when you import all quickstarts from the root POM, and also means there is no way to run this build from the root.

Instead you should just read Testing the quickstarts at http://www.jboss.org/jdf/about/contributing/#quickstarts which explains how to test the quickstarts.

**Comment by OndraZizka** [comment]
My suggestion was to make this test part of a profile.
I.e. `mvn test` would run without any prerequisites.
And to run tests which need X or Y to be done before, user would have to add some `-DbuildQuickstartFoo`

**Comment by pmuir** [comment]
But which tests run by default? It depends on your environment.

**Comment by sgilda** [comment]
This is now my JIRA and I have no idea how to resolve it: https://issues.jboss.org/browse/JBPAPP6-1706

**Comment by pmuir** [comment]
@sgilda we could disable that profile by default, but it's better to just configure the job properly to skip that profile.

**Comment by sgilda** [comment]
@pmuir: who can do that?

**Comment by OndraZizka** [comment]
I am a bit confused:
We don't want to put it to a profile, or are choosing the technical solution?

I can do that if I have an ACK from Pete on putting the module to a profile.

**Comment by pmuir** [comment]
I don't understand. The module is in a profile already but the profile is activeByDefault. So you can easily exclude the profile from any build by using -P!complex-dependencies

**Pull request closed without merging**
