### PR TITLE
Merge of latest community quickstarts to EAP.

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by sgilda** [comment]
This doesn't look right. My last commit was # eecb0c7420034feacd496978e5660340cf55dd9a with comment "Removed the WFK quickstarts"
Closing this pull for now.

**Comment by sgilda** [comment]
The commits seem to be in reverse order. Reopening the pull.

**Comment by pmuir** [comment]
Looks good to me.

**Comment by sgilda** [comment]
@pmuir: Should I go ahead and merge to `master-eap6`? I'm nervous because `master-eap60` only appears when you cliick on "View Merged Branches".

**Comment by pmuir** [comment]
That sounds good in fact - it shows this is a fast forward of master-eap60

**Comment by sgilda** [comment]
@pmuir: I just want to make sure I'm issuing  the right command here so I don't mess things up. :-)

FYI:
My remote repo name is jboss-eap.
My branch name is master-eap6.

Is this correct:  `git push jboss-eap HEAD:master-eap6`

**Comment by pmuir** [comment]
Yes, sounds good.

**Pull request merged**
