### PR TITLE
Eap issue 33

### PR DESCRIPTION
**Pull request by sgilda**
Remove OpenShift warning. Clarify contributor instructions in README template.

### CODE REVIEW

**Comment by sgilda** [comment]
I just realized the instructions for OpenShift refer to the "jbossas-7" container. Do the EAP deployments use a different container?

**Comment by sgilda** [comment]
Hold off on this. Modifying the instructions for EAP6 application types.

**Comment by sgilda** [comment]
Pete, I believe this is ready to go.

**Comment by sgilda** [comment]
Hold off on this one. I'm making more modifications.

**Comment by sgilda** [comment]
I fixed the community issue with this pull: https://github.com/jboss-jdf/jboss-as-quickstart/issues/291
I also modified the README files to add the rest prefix.
I think this one is ready now. :-)

**Comment by pgier** [comment]
Merged 76d95d433bedd5e65b7d6a2c411bb289a799c053

**Pull request closed without merging**
