### PR TITLE
Add wfk quickstarts

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by sgilda** [comment]
The description says "Add wfk quickstarts" but the commit appears to remove all the non-wfk quickstarts. Is this intentional?

**Comment by pmuir** [comment]
Yes - note this should be merged to the wfk-master branch.

**Comment by sgilda** [comment]
I will wait to push this when you're around, just in case I need help. :-)

**Comment by kpiwko** [comment]
When applying pull request on wfk-master, after solving conflicts it seems that wfk-master is old when compared to eap-master, because wfk-related quickstarts sources are not present at all.

```
[ERROR]   The project org.jboss.as.quickstarts:jboss-as-quickstarts-parent:7.1.1.CR2 (/home/kpiwko/devel/wfk/sandbox/wfk-2.0/quickstart/pom.xml) has 4 errors
[ERROR]     Child module /home/kpiwko/devel/wfk/sandbox/wfk-2.0/quickstart/helloworld-errai of /home/kpiwko/devel/wfk/sandbox/wfk-2.0/quickstart/pom.xml does not exist
[ERROR]     Child module /home/kpiwko/devel/wfk/sandbox/wfk-2.0/quickstart/helloworld-gwt/pom.xml of /home/kpiwko/devel/wfk/sandbox/wfk-2.0/quickstart/pom.xml does not exist
[ERROR]     Child module /home/kpiwko/devel/wfk/sandbox/wfk-2.0/quickstart/helloworld-jsf/pom.xml of /home/kpiwko/devel/wfk/sandbox/wfk-2.0/quickstart/pom.xml does not exist
[ERROR]     Child module /home/kpiwko/devel/wfk/sandbox/wfk-2.0/quickstart/richfaces-validation of /home/kpiwko/devel/wfk/sandbox/wfk-2.0/quickstart/pom.xml does not exist
```

**Comment by pmuir** [comment]
I'll re make the branch

**Comment by pmuir** [comment]
Please try now, I pushed the wrong thing before ;-)

**Comment by kpiwko** [comment]
Verified, compiles fine.

**Comment by sgilda** [comment]
I pushed before I saw this thread. What do I need to do now?

**Comment by sgilda** [comment]
I pushed this to jboss-eap/wfk-master before seeing all these other 
comments. Please advise.

**Comment by kpiwko** [comment]
Merging Pete's pull request on top of current wfk-master once more extra should do the trick.

**Comment by sgilda** [comment]
I tried checking out his branch again with a new name, did the rebase jboss-eap/wfk-master, and every file has a conflict. Not sure what to do now.

quickstart (add-wfk-2) $ git rebase jboss-eap/wfk-master 
First, rewinding head to replay your work on top of it...
Applying: Remove eap quickstarts
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
CONFLICT (rename/delete): Rename bean-validation/README.html->richfaces-validation/README.html in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename bean-validation/pom.xml->richfaces-validation/pom.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename bean-validation/src/main/java/org/jboss/as/quickstarts/kitchensink/model/Member.java->richfaces-validation/src/main/java/org/jboss/as/quickstarts/richfaces_validation/Member.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename bean-validation/src/test/java/org/jboss/as/quickstarts/kitchensink/test/MemberValidationTest.java->richfaces-validation/src/test/java/org/jboss/as/quickstarts/kitchensink/test/MemberValidationTest.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename bean-validation/src/test/resources/META-INF/test-persistence.xml->richfaces-validation/src/test/resources/META-INF/test-persistence.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename bmt/src/main/webapp/WEB-INF/beans.xml->helloworld-errai/src/main/webapp/WEB-INF/beans.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename bmt/src/main/webapp/index.html->helloworld-errai/src/main/webapp/HelloWorldApp.html in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename cdi-injection/README.md->helloworld-jsf/README.md in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename cdi-injection/src/main/webapp/WEB-INF/faces-config.xml->helloworld-gwt/src/main/java/org/jboss/as/quickstarts/gwthelloworld/client/local/HelloWorldClient.ui.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename cmt/src/main/java/org/jboss/as/quickstarts/cmt/model/Customer.java->helloworld-jsf/src/main/java/org/jboss/as/quickstarts/jsf/RichBean.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename cmt/src/main/webapp/WEB-INF/hornetq-jms.xml->helloworld-gwt/src/main/java/org/jboss/as/quickstarts/gwthelloworld/HelloWorldApp.gwt.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename ejb-in-ear/web/src/main/webapp/WEB-INF/beans.xml->helloworld-gwt/src/main/webapp/WEB-INF/beans.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename ejb-in-ear/web/src/main/webapp/WEB-INF/faces-config.xml->helloworld-jsf/src/main/webapp/WEB-INF/faces-config.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename ejb-in-ear/web/src/main/webapp/index.html->helloworld-gwt/src/main/webapp/HelloWorldApp.html in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename ejb-in-war/src/main/webapp/WEB-INF/beans.xml->helloworld-jsf/src/main/webapp/WEB-INF/beans.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename ejb-remote/client/src/main/resources/jboss-ejb-client.properties->helloworld-errai/src/main/resources/log4j.properties in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename ejb-security/src/main/webapp/WEB-INF/jboss-web.xml->helloworld-errai/src/main/java/org/jboss/as/quickstarts/erraihelloworld/HelloWorldApp.gwt.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename ejb-security/src/main/webapp/WEB-INF/web.xml->helloworld-errai/src/main/java/org/jboss/as/quickstarts/erraihelloworld/client/local/HelloWorldClient.ui.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename greeter/pom.xml->template/pom.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename greeter/src/main/java/org/jboss/as/quickstarts/greeter/domain/UserDao.java->dist/license.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld-html5/LICENSE.txt->LICENSE.txt in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld-osgi/README.html->helloworld-errai/README.html in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld-rs/src/main/java/org/jboss/as/quickstarts/rshelloworld/HelloService.java->helloworld-gwt/src/main/java/org/jboss/as/quickstarts/gwthelloworld/server/HelloService.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld-rs/src/main/java/org/jboss/as/quickstarts/rshelloworld/HelloWorld.java->helloworld-errai/src/main/java/org/jboss/as/quickstarts/erraihelloworld/client/shared/HelloWorldResource.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld-singleton/README.html->helloworld-gwt/README.html in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld-singleton/README.md->helloworld-errai/README.md in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld-singleton/src/main/java/org/jboss/as/quickstarts/singleton/Counter.java->helloworld-gwt/src/main/java/org/jboss/as/quickstarts/gwthelloworld/client/local/HelloWorldApp.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld-singleton/src/main/webapp/index.html->dist/license.html in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld/README.html->helloworld-jsf/README.html in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename helloworld/src/main/java/org/jboss/as/quickstarts/helloworld/HelloService.java->helloworld-errai/src/main/java/org/jboss/as/quickstarts/erraihelloworld/server/HelloService.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename hibernate3/src/main/webapp/WEB-INF/beans.xml->richfaces-validation/src/main/webapp/WEB-INF/beans.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename hibernate3/src/main/webapp/WEB-INF/faces-config.xml->dist/src/main/assembly/assembly.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename hibernate3/src/main/webapp/WEB-INF/hibernate3-quickstart-ds.xml->richfaces-validation/src/main/webapp/WEB-INF/richfaces-validation-quickstart-ds.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename hibernate3/src/main/webapp/index.html->richfaces-validation/src/main/webapp/index.html in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename kitchensink-ear/README.md->richfaces-validation/README.md in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename kitchensink-ear/jboss-as-kitchensink-ear-ejb/src/test/resources/arquillian.xml->richfaces-validation/src/test/resources/arquillian.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename kitchensink-ear/jboss-as-kitchensink-ear-ejb/src/test/resources/test-ds.xml->richfaces-validation/src/test/resources/test-ds.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename kitchensink/src/main/resources/META-INF/persistence.xml->richfaces-validation/src/main/resources/META-INF/persistence.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename log4j/src/main/webapp/index.html->dist/license.xhtml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename logging-tools/src/main/resources/org/jboss/as/quickstarts/loggingToolsQS/exceptions/DateExceptionsBundle.i18n_locale_COUNTRY_VARIANT.properties->helloworld-errai/src/main/resources/ErraiService.properties in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename logging-tools/src/main/resources/org/jboss/as/quickstarts/loggingToolsQS/messages/GreetingMessagesBundle.i18n_locale_COUNTRY_VARIANT.properties->dist/license.properties in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename logging-tools/src/main/resources/org/jboss/as/quickstarts/loggingToolsQS/messages/GreetingMessagesBundle.i18n_sv_SE.properties->helloworld-errai/src/main/resources/ErraiApp.properties in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename logging-tools/src/main/webapp/WEB-INF/web.xml->helloworld-jsf/src/main/webapp/WEB-INF/web.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename numberguess/pom.xml->helloworld-jsf/pom.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename payment-cdi-event/src/main/java/org/jboss/as/quickstarts/payment/resources/Resources.java->richfaces-validation/src/main/java/org/jboss/as/quickstarts/richfaces_validation/Resources.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename servlet-filterlistener/README.md->helloworld-gwt/README.md in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename tasks-jsf/src/main/java/org/jboss/as/quickstarts/tasksJsf/CurrentTask.java->richfaces-validation/src/main/java/org/jboss/as/quickstarts/richfaces_validation/NewMember.java in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename tasks-jsf/src/main/webapp/WEB-INF/faces-config.xml->richfaces-validation/src/main/webapp/WEB-INF/faces-config.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename wsat-simple/src/main/webapp/WEB-INF/classes/context-handlers.xml->helloworld-gwt/src/main/webapp/WEB-INF/web.xml in HEAD and deleted in Remove eap quickstarts
CONFLICT (rename/delete): Rename xml-jaxp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml->dist/license.xml in HEAD and deleted in Remove eap quickstarts
Failed to merge in the changes.
Patch failed at 0001 Remove eap quickstarts

When you have resolved this problem run "git rebase --continue".
If you would prefer to skip this patch, instead run "git rebase --skip".
To restore the original branch and stop rebasing run "git rebase --abort".

**Comment by kpiwko** [comment]
Hmm, rebasing would really be nasty. I have succeeded with a recursive merge though:

```
git fetch jbosseap
git fetch pmuir
git checkout jbosseap/wfk-master -b wfk-master
git merge pmuir/add-wfk-quickstarts
```

Not really nice in history view, but does the work.

**Comment by pmuir** [comment]
Do you want me to just push the result, there is nothing complex here.

**Comment by kpiwko** [comment]
Yes, push it. IMHO you can even rewrite history, cause only three people will be affected.

**Comment by pmuir** [comment]
This all looks fine.

**Comment by sgilda** [comment]
Pete, what did you have to do to fix my push?

**Comment by pmuir** [comment]
Nothing, it looks fine as is to me.

I think the confusion was that my patch remained the same, but I had to fix the underlying jboss-eap/jboss-bom master-wfk branch to look right.

You merged and pushed after I did that fix.

**Comment by sgilda** [comment]
I guess I lucked out. Thanks for the update!

**Pull request closed without merging**
